### ISSUE TITLE
Minimum Mac OS X should be 10.13 but not working OOB

### ISSUE THREAD

**Issue by elosha** [TomHarte/CLK#1143]
### Situation

I have an old MacPro5,1 that runs High Sierra (Mac OS X 10.13) which I use for my hobby stuff. According to info.plist this should be enough.

But I get this error:
> Termination Reason:    DYLD, [0x1] Library missing
> 
> Application Specific Information:
> dyld: launch, loading dependent libraries
> 
> Dyld Error Message:
>  Library not loaded: @rpath/libswiftCore.dylib
>  Referenced from: /private/var/folders/*/Clock Signal.app/Contents/MacOS/Clock Signal
>  Reason: image not found

However the missing library exists in /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib

### Questions

1. Can I get it to work by symlinking the missing lib from somewhere, adding a search path, etc.?
2. Can you fix linking so it actually works on 10.13? :)

### System
- Clock Signal Official Build 2023-05-15
- Mac OS X 10.13.6
- MacPro5,1
- Intel X5650
- Nvidia K4000
- 32GB RAM

**Comment by elosha** [comment]
Sorry, clone of #1118. But now you know that and where the lib exists :)

**Comment by TomHarte** [comment]
If [Clock Signal.zip](https://github.com/TomHarte/CLK/files/12516002/Clock.Signal.zip) works then everything is fixed. Fingers crossed.

**Comment by elosha** [comment]
Thanks for the build!

Sadly, it still doesn't:

> Termination Reason:    DYLD, [0x1] Library missing
> 
> Application Specific Information:
> dyld: launch, loading dependent libraries
> 
> Dyld Error Message:
>   Library not loaded: @rpath/libswiftCore.dylib
>   Referenced from: /Applications/Clock Signal.app/Contents/MacOS/Clock Signal
>   Reason: no suitable image found.  Did find:
> 	/System/Library/PrivateFrameworks/Swift/libswiftCore.dylib/libswiftCore.dylib: stat() failed with errno=20

"**no suitable image found**" – never had this error before. Seems a plethora of things can be the reason, even code signing …
